name: "🐛 Bug report"
description: "Report a bug in StatusCord"
title: "[Bug] - "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Please fill in the details below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: "📝 Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug here..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📋 Logs"
      description: "Relevant log files or error messages."
      placeholder: "Paste logs here..."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: "ℹ️ Additional Information"
      description: "Any additional context or information."
      placeholder: "Additional context here..."

  - type: dropdown
    id: version
    attributes:
      label: "🔢 Plugin Version"
      description: "Plugin version."
      options:
        - 1.0.0
        - Other
    validations:
      required: true

  - type: input
    id: server_version
    attributes:
      label: "🖥️ Server Version"
      description: "The Minecraft server version you're using."
      placeholder: "e.g., Paper 1.16.5"
    validations:
      required: true
