# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Official Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact Build
      uses: actions/upload-artifact@v4
      with:
        name: StatusCord BuildTarget
        path: target/*

    - name: Upload Artifact Jar
      uses: actions/upload-artifact@v4
      with:
        name: StatusCord PluginJar
        path: target/StatusCord.jar
